/**
 * Converts structured meeting minutes JSON into Slack Block Kit format.
 * Produces a beautiful, well-organized message with sections and emojis.
 */

/**
 * Format meeting minutes as Slack Block Kit blocks.
 * @param {object} minutes - Structured minutes from Gemini
 * @returns {Array} Slack Block Kit blocks array
 */
export function formatMinutesAsBlocks(minutes) {
    const blocks = [];

    // Header
    blocks.push({
        type: 'header',
        text: { type: 'plain_text', text: `📋 ${minutes.title || 'Meeting Minutes'}`, emoji: true },
    });

    // Meta info
    const metaParts = [];
    if (minutes.date) metaParts.push(`📅 ${minutes.date}`);
    if (minutes.duration) metaParts.push(`⏱️ ${minutes.duration}`);
    if (minutes.languagesDetected?.length) {
        metaParts.push(`🌐 ${minutes.languagesDetected.join(', ')}`);
    }
    if (metaParts.length) {
        blocks.push({
            type: 'context',
            elements: [{ type: 'mrkdwn', text: metaParts.join('  •  ') }],
        });
    }

    blocks.push({ type: 'divider' });

    // Summary
    if (minutes.summary) {
        blocks.push({
            type: 'section',
            text: { type: 'mrkdwn', text: `*📝 Summary*\n${minutes.summary}` },
        });
        blocks.push({ type: 'divider' });
    }

    // Discussion Topics
    if (minutes.discussionTopics?.length) {
        let topicsText = '*💬 Discussion Topics*\n';
        minutes.discussionTopics.forEach((t, i) => {
            topicsText += `\n*${i + 1}. ${t.topic}*\n${t.summary}\n`;
        });
        blocks.push({ type: 'section', text: { type: 'mrkdwn', text: topicsText } });
        blocks.push({ type: 'divider' });
    }

    // Decisions
    if (minutes.decisions?.length) {
        let decisionsText = '*🔨 Decisions*\n';
        minutes.decisions.forEach((d) => {
            decisionsText += `\n• *${d.decision}*`;
            if (d.rationale) decisionsText += `\n  _Rationale: ${d.rationale}_`;
            if (d.owner) decisionsText += `\n  👤 Owner: ${d.owner}`;
            decisionsText += '\n';
        });
        blocks.push({ type: 'section', text: { type: 'mrkdwn', text: decisionsText } });
        blocks.push({ type: 'divider' });
    }

    // Action Items (TODOs)
    if (minutes.actionItems?.length) {
        const priorityEmoji = { high: '🔴', medium: '🟡', low: '🟢' };
        let actionsText = '*✅ Action Items*\n';
        minutes.actionItems.forEach((a) => {
            const emoji = priorityEmoji[a.priority] || '⚪';
            actionsText += `\n${emoji} *${a.task}*`;
            if (a.assignee) actionsText += `\n  👤 ${a.assignee}`;
            if (a.deadline) actionsText += `  •  📅 ${a.deadline}`;
            actionsText += '\n';
        });
        blocks.push({ type: 'section', text: { type: 'mrkdwn', text: actionsText } });
        blocks.push({ type: 'divider' });
    }

    // Deadlines
    if (minutes.deadlines?.length) {
        let deadlinesText = '*📅 Deadlines*\n';
        minutes.deadlines.forEach((d) => {
            deadlinesText += `\n• *${d.item}* — ${d.date}`;
            if (d.owner) deadlinesText += ` (${d.owner})`;
        });
        blocks.push({ type: 'section', text: { type: 'mrkdwn', text: deadlinesText } });
        blocks.push({ type: 'divider' });
    }

    // Feedback
    if (minutes.feedback?.length) {
        const sentimentEmoji = { positive: '👍', negative: '👎', neutral: '💭' };
        let feedbackText = '*💡 Feedback*\n';
        minutes.feedback.forEach((f) => {
            const emoji = sentimentEmoji[f.sentiment] || '💭';
            feedbackText += `\n${emoji} *${f.about}*: ${f.content}`;
        });
        blocks.push({ type: 'section', text: { type: 'mrkdwn', text: feedbackText } });
        blocks.push({ type: 'divider' });
    }

    // Follow-ups
    if (minutes.followUps?.length) {
        let followUpText = '*🔄 Follow-ups*\n';
        minutes.followUps.forEach((f) => {
            followUpText += `\n• *${f.topic}*\n  ${f.nextSteps}\n`;
        });
        blocks.push({ type: 'section', text: { type: 'mrkdwn', text: followUpText } });
    }

    // Footer
    blocks.push({
        type: 'context',
        elements: [{
            type: 'mrkdwn',
            text: '🤖 _Generated by Huddle Minutes Bot • Powered by Gemini AI_',
        }],
    });

    return blocks;
}

/**
 * Format minutes as a plain text fallback (for notifications).
 * @param {object} minutes
 * @returns {string}
 */
export function formatMinutesAsText(minutes) {
    let text = `📋 ${minutes.title || 'Meeting Minutes'}\n`;
    if (minutes.summary) text += `\n${minutes.summary}\n`;
    if (minutes.actionItems?.length) {
        text += `\n✅ Action Items: ${minutes.actionItems.length}`;
    }
    if (minutes.deadlines?.length) {
        text += `\n📅 Deadlines: ${minutes.deadlines.length}`;
    }
    return text;
}
